// <auto-generated />
using System;
using Chen_Xuxian_HW5.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chen_Xuxian_HW5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181030004418_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Chen_Xuxian_HW5.Models.Language", b =>
                {
                    b.Property<int>("LanguageID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("LanguageID");

                    b.ToTable("Languages");
                });

            modelBuilder.Entity("Chen_Xuxian_HW5.Models.Repository", b =>
                {
                    b.Property<int>("RepositoryID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<int?>("LanguageID");

                    b.Property<DateTime>("LastUpdate");

                    b.Property<string>("RepositoryName");

                    b.Property<decimal>("StarCount");

                    b.Property<string>("Tags");

                    b.Property<string>("URL");

                    b.Property<string>("UserName");

                    b.HasKey("RepositoryID");

                    b.HasIndex("LanguageID");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Chen_Xuxian_HW5.Models.Repository", b =>
                {
                    b.HasOne("Chen_Xuxian_HW5.Models.Language", "Language")
                        .WithMany("Repositories")
                        .HasForeignKey("LanguageID");
                });
#pragma warning restore 612, 618
        }
    }
}
